### PR TITLE
fix issue #1

### PR DESCRIPTION
**Pull request by RedTeaDev**
fix issue #1 

aaaaunknown

uaaaaaaanknown

### CODE REVIEW

**Comment by samueltangz** [comment]
Test cases not passed:
* https://github.com/samueltangz/ctf-archive-created/tree/master/20201006-hkcert-ctf/sanity-check#solves
* https://github.com/samueltangz/ctf-archive-created/tree/master/20201006-hkcert-ctf/lf2#solves

They are still showing 74 instead of 84.

**Comment by RedTeaDev** [comment]
🤦 merge them

**Comment by RedTeaDev** [comment]
oh fixed

**Comment by samueltangz** [comment]
That is the greatest commit in 2020! Thanks!

**Pull request merged**
